version: '3.0'
services:
  nginx:
   image: nginx:latest
     
   volumes:
       - ./:/var/www/
       - ./nginx/conf.d/:/etc/nginx/conf.d
   ports:
    - "80:80"
   depends_on: 
          - app
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
        - ./:/var/www/ 
        - ./_docker/php-fpm.d/www.conf:/usr/local/etc/www.conf
